import { ActionIcon, Badge, Button, Card, Code, CopyButton, Group, SimpleGrid, Stack, Text, Title, Tooltip } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconActivity, IconCheck, IconCopy, IconServer, IconTerminal2 } from "@tabler/icons-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router";
import { getSister, formatBytes, formatUptime, pingSister } from "../api";
import { EmptyState, ErrorState, LoadingState } from "../components/StateViews";

export function SisterDetailPage() {
  const id = useParams().id ?? "";
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["sister", id], queryFn: () => getSister(id), enabled: id.length > 0, refetchInterval: 3000, refetchIntervalInBackground: false });
  const ping = useMutation({ mutationFn: () => pingSister(id), onSuccess: () => { notifications.show({ title: "Sister reachable", message: `Ping to #${id} completed.`, color: "teal" }); void queryClient.invalidateQueries({ queryKey: ["sisters"] }); }, onError: (error: Error) => notifications.show({ title: "Ping failed", message: error.message, color: "red" }) });
  if (query.isLoading) return <LoadingState />;
  if (query.isError) return <Stack gap="lg"><Button component={Link} to="/sisters" variant="subtle" w="fit-content">← Back to Sisters</Button><ErrorState error={query.error} onRetry={() => void query.refetch()} /></Stack>;
  if (!query.data) return <EmptyState title="Sister not found" message="Return to the Sister list and choose a known node." />;
  const sister = query.data;
  return <Stack gap="xl"><Group justify="space-between" align="flex-end"><div><Text className="eyebrow">Network / Sister detail</Text><Title order={1} mt={6}>{sister.nickname}</Title><Text c="dimmed" mt={6} className="mono">#{sister.id} · {sister.hostname}</Text></div><Group><Button variant="subtle" component={Link} to="/sisters">All Sisters</Button><Button leftSection={<IconActivity size={16} />} loading={ping.isPending} onClick={() => ping.mutate()}>Ping Sister</Button></Group></Group><SimpleGrid cols={{ base: 1, md: 2 }}><Card radius="lg" withBorder><Group justify="space-between" mb="lg"><Group gap="sm"><IconServer size={19} color="#67e8f9" /><Title order={4}>Identity</Title></Group><Badge color={sister.status === "online" ? "teal" : "gray"} variant="light">{sister.status}</Badge></Group><Stack gap="md"><Detail label="Platform" value={sister.platform} /><Detail label="Version" value={sister.version} /><Detail label="Uptime" value={formatUptime(sister.uptime_secs)} /><Detail label="Control endpoint" value={sister.control_endpoint} copy /></Stack></Card><Card radius="lg" withBorder><Group gap="sm" mb="lg"><IconTerminal2 size={19} color="#8b5cf6" /><Title order={4}>Resources</Title></Group><SimpleGrid cols={2}><Detail label="CPU" value={`${sister.cpu_usage.toFixed(1)}%`} /><Detail label="Memory" value={`${formatBytes(sister.memory_used)} / ${formatBytes(sister.memory_total)}`} /><Detail label="Running jobs" value={`${sister.running_jobs}`} /><Detail label="Queued jobs" value={`${sister.queued_jobs}`} /></SimpleGrid></Card></SimpleGrid><Card radius="lg" withBorder><Text className="eyebrow">Reachability</Text><Title order={4} mt={4} mb="lg">Known connection routes</Title>{sister.stream_endpoints.length ? <Stack gap="xs">{sister.stream_endpoints.map((endpoint) => <Code key={endpoint} block>{endpoint}</Code>)}</Stack> : <Text c="dimmed" size="sm">No long-lived stream endpoint is advertised by this Sister yet.</Text>}</Card></Stack>;
}

function Detail({ label, value, copy = false }: { label: string; value: string; copy?: boolean }) { return <Group justify="space-between" wrap="nowrap" align="flex-start"><Text size="sm" c="dimmed">{label}</Text>{copy ? <CopyButton value={value}>{({ copied, copy: doCopy }) => (<Group gap={5} wrap="nowrap"><Text size="sm" className="mono" ta="right">{value}</Text><Tooltip label={copied ? "Copied" : "Copy"}><ActionIcon size="sm" variant="subtle" color={copied ? "teal" : "gray"} onClick={doCopy}>{copied ? <IconCheck size={14} /> : <IconCopy size={14} />}</ActionIcon></Tooltip></Group>)}</CopyButton> : <Text size="sm" className="mono" ta="right">{value}</Text>}</Group>; }
